ALTER TABLE devices_status ADD COLUMN IF NOT EXISTS chk_volt BOOLEAN DEFAULT true;
ALTER TABLE devices_status ADD COLUMN IF NOT EXISTS chk_bat BOOLEAN DEFAULT true;
ALTER TABLE devices_status ADD COLUMN IF NOT EXISTS chk_temp BOOLEAN DEFAULT true;
ALTER TABLE devices_status ADD COLUMN IF NOT EXISTS chk_door BOOLEAN DEFAULT true;
