# Nome da aplicacao
spring.application.name=smartrf-backend

# Porta do servidor interna (o Docker redireciona para a externa)
server.port=8080

# -------------------------
# BANCO DE DADOS (SUPABASE)
# -------------------------
spring.datasource.url=${SUPABASE_JDBC_URL}
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASS}
# Compatibilidade com o Transaction Pooler do Supabase (PgBouncer)
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Desabilita o open-in-view para melhor performance de conexao
spring.jpa.open-in-view=false

# -------------------------
# MQTT
# -------------------------
mqtt.broker.url=${MQTT_BROKER_URL:tcp://mosquitto:1883}
mqtt.client.id=smartrf-backend-client

# -------------------------
# ENVIO DE E-MAILS (SMTP)
# -------------------------
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
